services:
  postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - marketplace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      # --- CORREÇÕES ABAIXO ---
      # Força o uso do Driver do PostgreSQL (sobrescreve o padrão H2 do application.properties)
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      # Força o dialeto correto para evitar erros de SQL
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      # ------------------------
      - MERCADO_PAGO_ACCESS_TOKEN=TEST-115918252371439-011820-13972a58589b65487bd392512e69e996-1171424632
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - marketplace-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8081/api
    depends_on:
      - backend
    networks:
      - marketplace-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: marketplace-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - marketplace-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres-data:
  rabbitmq_data:

networks:
  marketplace-network:
    driver: bridge