
services:
  postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - marketplace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - MERCADO_PAGO_ACCESS_TOKEN=TEST-0000000000000000-000000-00000000000000000000000000000000-00000000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - marketplace-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8081/api
    depends_on:
      - backend
    networks:
      - marketplace-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: marketplace-rabbitmq
    ports:
      - "5672:5672"   # Porta padrão de comunicação
      - "15672:15672" # Painel de administração (Web UI)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - marketplace-network
volumes:
  postgres-data:

networks:
  marketplace-network:
    driver: bridge

